In [4]:
import numpy as np

In [5]:
mylist = [1,2,3,4]

In [6]:
np.array(mylist)

array([1, 2, 3, 4])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,12,4)

array([ 0.,  4.,  8., 12.])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(1)

array([0.75476788])

In [18]:
np.random.randn(10)

array([ 0.3674711 , -1.96738648, -0.34962377, -0.94007297,  0.76869833,
       -0.97173948,  2.19682889,  1.65332187,  1.16799741,  1.1610459 ])

In [19]:
np.random.randint(0,101,5)

array([85, 10, 99, 99, 85])

In [20]:
np.random.randint(0,101,(3,2))

array([[13, 28],
       [57, 15],
       [29, 99]])

In [21]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [22]:
arr = np.arange(0,20)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
xyz = np.random.randint(0,101,10)

In [27]:
xyz

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [28]:
xyz.min()

2

In [29]:
xyz.max()

99

In [30]:
xyz.dtype

dtype('int32')

In [31]:
xyz.argmax()

5

In [32]:
xyz.argmin()

7

In [33]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
total_rolls_over_two = len(dice_rolls[dice_rolls>2])

In [34]:
total_rolls_over_two

19

In [35]:
dice_rolls[dice_rolls>2]

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [36]:
dice_rolls>2

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [37]:
#numpy Index & selection

In [38]:
arr = np.arange(0,11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[8]

8

In [41]:
arr[1:5]

array([1, 2, 3, 4])

In [42]:
arr[:4]

array([0, 1, 2, 3])

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[:5] = 100

In [45]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [46]:
slice1 = arr[5:]

In [47]:
slice1

array([ 5,  6,  7,  8,  9, 10])

In [48]:
slice1 [:] = 99

In [49]:
slice1

array([99, 99, 99, 99, 99, 99])

In [50]:
arr

array([100, 100, 100, 100, 100,  99,  99,  99,  99,  99,  99])

In [51]:
arr_copy = arr.copy()

In [52]:
arr = np.arange(1,4)

In [53]:
arr

array([1, 2, 3])

In [54]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [55]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d.shape

(3, 3)

In [57]:
arr_2d [0,2]

15

In [58]:
arr_2d [1][0]

20

In [59]:
arr_2d [:2,1:]

array([[10, 15],
       [25, 30]])

In [60]:
#conditional selection filter

In [61]:
arr = np.arange (1,11)

In [62]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [64]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [65]:
#numpy operation

In [66]:
arr = np.arange(0,10)

In [68]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr +5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [71]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
arr/arr

<ipython-input-72-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [73]:
1/arr

<ipython-input-73-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [74]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [76]:
np.sum(arr)

45

In [77]:
arr.sum()

45

In [78]:
np.mean(arr)

4.5

In [79]:
arr.mean()

4.5

In [80]:
arr.max()

9

In [81]:
arr.var()

8.25

In [82]:
arr.std()

2.8722813232690143

In [86]:
arr2d = np.arange(0,25).reshape(5,5)

In [90]:
arr2d.shape

(5, 5)

In [91]:
arr2d.sum()

300

In [95]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [97]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])