In [1]:
import numpy as np

In [2]:
#question 1
#you are creating an array 'arange' for the following code:
arr1 = np.arange(30,40,2)
arr2 = np.arange(5)
arr3 = np.arange(40,30,-1)

#what will be the output of the following lines?
print(arr1)
print(arr2)
print(arr3)

[30 32 34 36 38]
[0 1 2 3 4]
[40 39 38 37 36 35 34 33 32 31]


In [3]:
#question 2
#what will be the output of the following statement

a = np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]


In [4]:
#question 3
#what will the following statement print?

a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print (a[...,1])

[2 4 5]


In [13]:
#question 4
#how can the identity matrix be formed into a non-invertible matrix?

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
#question 5
#what will be the putput of the followiing code?
a = np.array([2,5,8])
print('average() funtion:')
print(np.average(a))

average() funtion:
5.0


In [26]:
#question 6
#which error will occur?

try:
    In = input()
    print(in/2)
except Exception as err:
    print(err)

SyntaxError: invalid syntax (37406767.py, line 6)

In [29]:
#question 7
#what will be the output of the following code?

def number_decorator (func):
    print("inside decorator")
    def wrapper(*args):
        print("Inside Wrapper")
        func(*args)
    return wrapper

@number_decorator
def process_nos(nums):
    print("inside process_nos")

process_nos([1,2,3])


inside decorator
Inside Wrapper
inside process_nos


In [34]:
#question 8
#what will be the output of the following code?

def mynos():
    for i in range(1,10):
        if i%3:
            yield(i)
    else:
        raise StopIteration

my_generator = mynos()
print(next(my_generator))
print(next(my_generator))
print(next(my_generator))

1
2
4


In [45]:
#question 9
#Identify the output that will be generated by given code?

import threading
def thread1():
    print("First thread")
def thread2():
    print("Second thread")
t1 = threading.Thread(target=thread1)
t2 = threading.Thread(target=thread2)
t1.start()
print("Main thread name: {}".format(threading.main_thread().name))

First thread
Main thread name: MainThread


In [53]:
#question 10
#In the given code snippet which among val1, val2, val3 and val4 will generate are an error on execution?

try:
    mytuple=(3.14, "Python", "Programming",1.3333333,"654.5")
    temp=tuple(list(mytuple))
    val1=len(temp)
    print(val1)

    val2=mytuple*2
    print(val2)

    temp = str(mytuple[::-1])
    val3 = "".join(temp)
    print(val3)

    mytuple[-4]=temp
    val4=mytuple[-1:]
    print(val4)

except TypeError:
    print("TypeError Occured")

#answer : val4

5
(3.14, 'Python', 'Programming', 1.3333333, '654.5', 3.14, 'Python', 'Programming', 1.3333333, '654.5')
('654.5', 1.3333333, 'Programming', 'Python', 3.14)
TypeError Occured


In [54]:
#question 11
# You are calculating Bayesian information Criterian(BIC) using thes below formula:
# a log(K) - 2log(L(B))

# What do the terms ‘a’ and 'K' refers in the above formula?




In [ ]:
#question 13
# you have two statistical models for which you need to compare the quality and then select the optimal model. On what basis will you say the model is optimal?

# ans: minimum of akaike information criterion and bayesian information criterion, highest r^2 values. 

#chat_gpt : Akaike Information Criterion (AIC), Bayesian Information Criterion (BIC), and R-squared (R^2) values are also commonly used to compare the quality of statistical models.
# A lower value of AIC or BIC indicates a better model fit, while a higher R^2 value indicates a better fit of the model to the data. These measures can be used in conjunction with other evaluation metrics to determine the optimal model.

In [1]:
#question 14

#what will be Entropy for the given data set?

# A = {x,x,x,y,y,y,y,y,y}

import numpy as np
from scipy.stats import entropy

# Define the dataset
dataset = ['x', 'x', 'x', 'y', 'y', 'y', 'y', 'y', 'y']

# Calculate the proportion of each value in the dataset
proportions = np.unique(dataset, return_counts=True)[1] / len(dataset)

# Calculate the entropy of the dataset using the proportions
entropy_value = entropy(proportions, base=2)

# Print the result
print('The entropy of the dataset is:', entropy_value)

The entropy of the dataset is: 0.9182958340544894


In [15]:
import math
x = math.sqrt(25) #25**0.5
y = math.pow(2,10)  #2**10
print(f"the value of x is {x}")
print(f"the value of y is {y}")

the value of x is 5.0
the value of y is 1024.0


In [16]:
import calendar

In [28]:
print(calendar.month(2023,4))

     April 2023
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30



In [6]:
from datetime import datetime

In [2]:
str(datetime.datetime.now()).split(" ")[0]

'2023-05-14'

In [13]:
td =str(datetime.now()).split(" ")[0]